modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-modifiedbiomesourceterrablender/issues"
license = "ARR"

[[mods]]
modId = "modifiedbiomesourceterrablender"
version = "${version}"
displayName = "Modified Biome Source - TerraBlender"
authors = "mahmudindev"
description = '''
Add compatibility between Modified Biome Source and TerraBlender.
'''
logoFile = "assets/modifiedbiomesourceterrablender/icon.png"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "modifiedbiomesource"
mandatory = true
versionRange = "[0.0.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "terrablender"
mandatory = true
versionRange = "[3.0.1,)"
ordering = "NONE"
side = "SERVER"
