modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-modifiedbiomesourceterrablender/issues"
license = "ARR"

[[mods]]
modId = "modifiedbiomesourceterrablender"
version = "${version}"
displayName = "Modified Biome Source - TerraBlender"
authors = "mahmudindev"
description = '''
Add compatibility between Modified Biome Source and TerraBlender.
'''
logoFile = "assets/modifiedbiomesourceterrablender/icon.png"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "modifiedbiomesource"
type = "required"
versionRange = "[0.0.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.modifiedbiomesourceterrablender]]
modId = "terrablender"
type = "required"
versionRange = "[4.2.0,)"
ordering = "NONE"
side = "SERVER"
